version = 1
exclude_patterns = [
  "dist/**",
  "examples/**"
]

test_patterns = ["*/test/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
