version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  exclude_patterns = [
  "dist/**",
  "examples/**"
  ]
  test_patterns = ["*/test/**"]
